name: rubocop-todo-corrector
description: Auto-correct RuboCop ToDo offenses and create pull request.
inputs:
  base_branch:
    description: Pull request base branch.
    required: false
    default: main
  mode:
    description: Mode to select deletion target.
    required: false
    default: random
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.1
    - run: gem install --no-document rubocop_todo_corrector:0.2.0
      shell: bash
    - uses: actions/checkout@v3
    - run: |
        rubocop_todo_corrector bundle
        rubocop_todo_corrector generate
        cop_name=$(rubocop_todo_corrector pick)
        rubocop_todo_corrector remove --cop-name="${cop_name}"
        rubocop_todo_corrector correct
        rubocop_todo_corrector generate
        git status
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git switch --create "rubocop-todo-corrector-${GITHUB_RUN_ID}"
        git add .
        git commit --message="Auto-correct ${cop_name}"
        rubocop_todo_corrector describe --cop-name="${cop_name}" \
          | gh pr create --title "Auto-correct ${cop_name}" --body-file -
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
branding:
  color: red
  icon: git-pull-request
