name: rubocop-todo-corrector
description: Auto-correct RuboCop ToDo offenses and create pull request.
inputs:
  base_branch:
    description: Pull request base branch.
    required: false
    default: main
  mode:
    description: Mode to select deletion target.
    required: false
    default: random
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.1
    - run: gem install --no-document rubocop_todo_corrector:0.2.0
      shell: bash
    - uses: actions/checkout@v3
    - run: |
        rubocop_todo_corrector bundle
        rubocop_todo_corrector generate
        git status
        cop_name="$(rubocop_todo_corrector pick)"
        rubocop_todo_corrector remove --cop-name="${cop_name}"
        rubocop_todo_corrector correct
        rubocop_todo_corrector generate
        git status
        rubocop_todo_corrector describe --cop-name="${cop_name}"
      shell: bash
branding:
  color: red
  icon: git-pull-request
